#!/bin/bash
sudo apt-get install openjdk-8-jdk
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0xA1183BDD2B0E0C6B
echo "deb https://dl.bintray.com/sonarsource/deb \
generic  stable" | sudo tee /etc/apt/sources.list.d/sonarqube.list
sudo apt-get update
sudo apt-get install sonarqube
sudo systemctl start sonarqube
